apiVersion: v1
kind: Service
metadata: { name: opensearch }
spec:
  selector: { app: opensearch }
  ports:
    - { name: http, port: 9200, targetPort: 9200 }
    - { name: diag, port: 9600, targetPort: 9600 }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: opensearch }
spec:
  replicas: 1
  selector: { matchLabels: { app: opensearch } }
  template:
    metadata: { labels: { app: opensearch } }
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2
          env:
            - { name: discovery.type, value: "single-node" }
            - { name: plugins.security.disabled, value: "true" }
            - { name: OPENSEARCH_JAVA_OPTS, value: "-Xms512m -Xmx512m" }
          ports:
            - { containerPort: 9200 }
            - { containerPort: 9600 }
