apiVersion: v1
kind: Service
metadata: { name: neo4j }
spec:
  selector: { app: neo4j }
  ports:
    - { name: http, port: 7474, targetPort: 7474 }
    - { name: bolt, port: 7687, targetPort: 7687 }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: neo4j }
spec:
  replicas: 1
  selector: { matchLabels: { app: neo4j } }
  template:
    metadata: { labels: { app: neo4j } }
    spec:
      containers:
        - name: neo4j
          image: neo4j:5
          env:
            - { name: NEO4J_AUTH, value: "neo4j/test" }
            - { name: NEO4J_dbms_security_procedures_unrestricted, value: "apoc.*" }
            - { name: NEO4JLABS_PLUGINS, value: "[\"apoc\"]" }
          ports:
            - { containerPort: 7474 }
            - { containerPort: 7687 }
